language: python
python:
  - 3.8
  - 3.9
env:
  - DJANGO=3.0.14
  - DJANGO=3.1.8
  - DJANGO=3.2
install:
  - pip install -e .
  - pip install -q Django==$DJANGO
script:
  - DJANGO_SETTINGS_MODULE=suit.tests.settings django-admin test suit
